import React from 'react';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import { useSettings } from '../../components/SettingsContext';

const TermsOfUse = () => {
    const settings = useSettings();

    return (
        <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-grow container mx-auto px-4 py-12">
                <h1 className="text-4xl font-bold mb-6 gradient-text">Terms of Use - Effective as of {settings.ToUEffectiveDate}</h1>

                <section className="mb-12">
                <h3 className="text font-semibold mb-4"><u>ACCEPTANCE OF TERMS AND CONDITIONS</u></h3>
                <p className="text font-semibold mb-4"><u>IMPORTANT</u> : THIS DOCUMENT CONSTITUTES A LEGAL AGREEMENT BETWEEN EACH END USER (REFERRED TO HEREIN AS "USER", "YOU", OR "YOUR") AND {settings.Company} (REFERRED TO HEREIN AS "{settings.Company}" OR "COMPANY"). BY ACCESSING AND USING THE {settings.Company} WEBSITE LOCATED AT {settings.URL} AND THE {settings.Company} APPLICATIONS (COLLECTIVELY REFERRED TO HEREIN AS THE "SERVICE"), YOU ARE BOUND BY THE TERMS AND CONDITIONS SET FORTH IN THIS AGREEMENT (REFERRED TO HEREIN AS THE "AGREEMENT" OR "TERMS" OR "TERMS OF USE"). THE SERVICE ENCOMPASSES VARIOUS COMPONENTS, INCLUDING TEXT, IMAGES, GRAPHICS, LOGOS, WORKS OF AUTHORSHIP, COMPUTER CODE, TRADE DRESS, TECHNICAL INFORMATION, AND OTHER CONTENT, AS WELL AS FEATURES AND SERVICES PROVIDED OR OFFERED THROUGH THE SITE (REFERRED TO COLLECTIVELY HEREIN AS THE "CONTENT"). FOR THE PURPOSES OF THESE TERMS OF USE, THE TERM "SITE" ALSO INCLUDES THE CONTENT, UNLESS SPECIFICALLY INDICATED OTHERWISE. BY USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE CAREFULLY READ AND UNDERSTOOD THIS AGREEMENT, INCLUDING ITS TERMS AND CONDITIONS, AND AGREE TO BE LEGALLY BOUND BY THEM. IF YOU DO NOT AGREE WITH ALL OF THE TERMS AND CONDITIONS OUTLINED IN THIS AGREEMENT, YOU ARE NOT GRANTED PERMISSION TO USE THE SERVICE, AND YOU MUST IMMEDIATELY CEASE ALL USE OF THE SERVICE. </p>

                <p><strong><br/>1. License Grant: This Agreement grants you a limited, non-exclusive, non-transferable, and non-sublicensable license ("License") to access and use the Services provided by {settings.Company}. The License is revocable and is valid for the duration of this Agreement. You may use the Services on a single computer, mobile phone, or other computing device for personal or internal business purposes only. {settings.Company} reserves the right to determine the content layout, formatting, features, and online or remote access processes or privileges for the Services. By accepting this Agreement, you acknowledge and agree to the following: 
                </strong></p><div className="square-ul">
                    <ul className='list-disc list-inside mb-4 font-semibold'><li>{settings.Company} retains the right to control and direct the means, manner, and method of providing the Service</li>
                        <li>{settings.Company} may engage independent contractors, consultants, or subcontractors to assist in providing the Service or its use, and </li>
                        <li>{settings.Company} has the right to provide the Service to others.</li> 
                    </ul></div><br/>
                    <strong>Please note that {settings.Company} can revoke this License at its sole discretion, with or without notice, and for any reason.</strong>
                </section>

                <p><strong><br/>2. LIMITATIONS ON USAGE:</strong>  All rights not explicitly granted under this Agreement are exclusively reserved by {settings.Company}. Therefore, you are strictly prohibited from utilizing the Service in any manner that is not explicitly and unequivocally authorized by this Agreement. Consequently, you are prohibited from modifying, reproducing, duplicating, copying, downloading, storing, transmitting, disseminating, transferring, disassembling, reverse engineering, decompiling, extracting source code, broadcasting, publishing, removing or altering any proprietary notices or labels, licensing, sublicensing, selling, mirroring, framing, renting, leasing, private labeling, granting a security interest in, creating derivative works of, or otherwise exploiting the Service or any portion thereof without prior written consent from {settings.Company}, except as expressly and unambiguously authorized herein. You are not permitted to engage in the following activities: 
                </p><div className="square-ul">
                    <ul className='list-disc list-inside mb-4 font-semibold'><li>attempting to gain unauthorized access to any part or feature of the Service or any other connected system or network, including {settings.Company} servers, by means of hacking, password "mining", or any other unauthorized or prohibited method; </li><li>probing, scanning, or testing the vulnerability of the Service or any connected network, or breaching the security or authentication measures of the Service or any connected network; </li><li>performing reverse look-ups or tracing any information about other users or visitors of the Service; </li><li>using any device, software, or routine to interfere with the proper functioning of the Service or any transaction conducted on the Service, or with another person's use of the Service; </li><li>forging headers, impersonating another person, or manipulating identifiers to conceal your identity or the origin of any message or transmission sent to {settings.Company} through the Service; </li><li>deleting, obscuring, or altering any warnings or links that appear in the Service; </li><li>registering, subscribing, attempting to register or subscribe, unsubscribing, or attempting to unsubscribe any party for any Service without express authorization; </li><li>bypassing phone-based verification systems, such as those used by Craigslist or Facebook; </li><li>facilitating remote computer repair or "virus removal" services; </li><li>using the Service in a manner that may subject {settings.Company} or any third party to liability, damages, legal violations, or danger; </li><li>engaging in unsolicited marketing messages or broadcasts, such as spam or bulk text messages that suggest cold outreach rather than one-to-one communication; </li><li>facilitating unsolicited ringless voicemail or using bandit signs in violation of applicable law; </li><li>sending calls to life-line services such as hospitals, fire departments, police stations, 911, or utility-related telephone numbers, or using multiple lines of a multi-line business, as it is unlawful; </li><li>interfering with another person's use and enjoyment of the Service; </li><li>collecting, using, or disclosing personal information of individuals (also known as "personally identifiable information", "PII", or "personal data") without obtaining legally valid consent or establishing a lawful basis for such processing activities; or </li><li>using the Service in an unlawful manner, including posting, uploading, transmitting, or making available any material that violates, misappropriates, or infringes upon the rights of others, is unlawful, threatening, abusive, defamatory, invasive of privacy or publicity rights, vulgar, obscene, profane, or otherwise objectionable, or encourages unlawful conduct.</li>
                    </ul>
                </div>
                
                <p>Any of the aforementioned uses may be considered as 'Misuse of the Service'. {settings.Company} reserves the right, at its sole discretion, to determine instances of 'Misuse' and may cooperate with legal authorities and/or third parties in investigating any suspected or alleged criminal or civil wrongdoing. Unless expressly limited by the Privacy Statement and Notice of Privacy Practices, {settings.Company} retains the right to disclose information deemed necessary to comply with applicable laws, regulations, legal processes, governmental requests, or to edit, refuse to post, or remove any information or materials, in whole or in part, at its sole discretion.</p>
                <p>Upon termination, regardless of the reason(s) for such termination, your right to use the Service available on this Site will immediately cease. We shall not be liable to you or any third party for any claims for damages arising from any termination, suspension, or other actions taken by us in connection with such termination. However, your liability for any unpaid fees shall survive any termination.</p>

                <p><strong><br/>3. Grant of General Rights to {settings.Company}:</strong>  By using the Service, you grant {settings.Company} certain rights as follows: 
                </p><div className="square-ul"><ul className='list-disc list-inside mb-4 font-semibold'>
                    <li><strong>Utilization of Device Resources:</strong>  You authorize {settings.Company} to utilize the processing power, bandwidth, and storage hardware of your mobile device or any other device you use to access the Service. This authorization is necessary to facilitate the proper operation of the Service.</li>
                    
                    <li><strong>Delivery of Advertising and Information:</strong>  You grant {settings.Company} the right to provide advertising and other relevant information to you through the Service.</li>
                    
                    <li><strong>Business Partner Involvement:</strong>  You allow {settings.Company} to permit our business partners to deliver advertising and other information to you through the Service.
                    
                    Regarding the above rights, you specifically authorize the Service to access your contacts and the associated information for the purpose of synchronizing with your phonebook directory.
                    
                    Moreover, you also grant {settings.Company} a non-exclusive, transferable, sublicensable, royalty-free, perpetual, irrevocable, fully paid, worldwide right and license to use, reproduce, display, publish, translate, modify, create derivative works from, and distribute the data and information you submit or provide to the Service. This includes any data collected by {settings.Company} during your use of the Service. Such usage may occur through any medium, either alone or in combination with other content or materials, employing any means, method, or technology, whether currently known or developed in the future.
                    
                    By granting these rights, you represent and warrant that you have obtained all necessary permissions to share the data and information you provide. Additionally, you confirm that you have no knowledge of any objections from your contacts regarding their names and phone numbers being included in the phonebook directory, which is accessible to other registered users.</li></ul></div>
                
                <p><strong><br/>4. Eligibility:</strong>  To create an account on {settings.Company} and access the Service, you must be at least 13 years of age. By creating an account and using the Service, you represent and warrant that you are eligible to use the Service under the applicable laws of the United States and other jurisdictions. This means that you are not listed on the U.S. Treasury Department's list of Specially Designated Nationals or subject to any similar prohibitions. Furthermore, you confirm that you have never been convicted of a felony or required to register as a sex offender.</p>
                
                <p><strong><br/>5. User Obligations:</strong>  By downloading, accessing, or using the Service, you agree to comply with the terms of this Agreement and all relevant local, state, and national laws and regulations. You also affirm that you have reached the legal age of majority in your jurisdiction. It is your responsibility to provide accurate, current, and complete information when submitting information through the Service, and you agree to cooperate with {settings.Company} in supporting the operation of the Service. Please note that additional notices, terms, and conditions may apply to the use of other {settings.Company} services or solutions. Furthermore, {settings.Company} does not guarantee specific results from using its service or any third-party service.</p>
                
                <p><strong><br/>6. CONTENT RESPONSIBILITY</strong></p>
                <div className="square-ul"><ul className='list-disc list-inside mb-4 font-semibold'>
                <li><strong>Website:</strong>  {settings.Company} assumes no responsibility for the usage or non-usage of the Service. There are no representations, warranties, or guarantees made by {settings.Company} regarding the truthfulness, accuracy, or reliability of any information exchanged through the Service. {settings.Company} does not endorse any opinions expressed by Users. Each User acknowledges and accepts that their use of the Service is at their own risk, and they are responsible for assessing whether such use may infringe upon any third-party intellectual property rights, privacy rights, or publicity rights. Users are solely responsible for the accuracy of the content they submit.</li>

                <li><strong>Downloads:</strong>  {settings.Company} does not guarantee that data available through the Service will be free from infection or viruses, worms, Trojan horses, or other malicious code that may cause harm or damage. It is your responsibility to implement appropriate safeguards and procedures to ensure that any downloaded data is free from such issues.</li>
                </ul></div>

                <p><strong><br/>7. OWNERSHIP:</strong>  The Service, including its Content, Site, user interface, code, data, graphics, logos, icons, images, audio files, data compilations, selection and format, as well as the underlying software and databases, are the exclusive property of {settings.Company} and are protected by national and international intellectual property laws. {settings.Company} holds all copyrights, trademarks, service marks, patents, trade secrets, and other intellectual property and proprietary rights to the fullest extent permitted by law. Users are prohibited from removing, concealing, or altering any copyright notice, byline information, disclaimer, restriction, or other notice on the Site. The use of the name, trademarks, trade names, or trade dress of {settings.Company} without the written consent of {settings.Company} is strictly prohibited.</p>

                <p><strong><br/>8. ACCOUNT:</strong>  To access the Service, you may need to register for an account. Each registration is for a single user, unless otherwise agreed upon by {settings.Company}. Registration may require specific access credentials, such as a username and password, or compliance with other designated access requirements determined by {settings.Company}. You are responsible for treating your access credentials as confidential information and must not disclose them to any third party without the prior written consent of {settings.Company}. You also assume full responsibility for all activities carried out under your username and password, and you must immediately notify {settings.Company} of any suspected loss, theft, or unauthorized use of your access credentials.
                
                User accounts are non-transferable, and users are responsible for preventing unauthorized access to the Site using their passwords. You are not permitted to assign these Terms, in whole or in part, or delegate your responsibilities to any third party without the written acknowledgment of {settings.Company}. {settings.Company} has the right, at its sole discretion, to assign these Terms, in whole or in part, or delegate its rights and responsibilities under these Terms to any third party or entity without prior notice.</p>

                <p><strong><br/>9. Fee and Subscription:</strong>  When you choose a paid Service plan, whether on a monthly or annual basis, you are agreeing to pay {settings.Company} the current subscription fees for that Service. These fees will be charged to you on the same day you sign up for the Service and will cover your use of the Service for the specified monthly or annual period. By selecting and providing payment for a Service plan, you also authorize {settings.Company}, or our payment affiliates or service providers, to process and/or store your payment card information. Additionally, you agree to pay all applicable fees for the Services, including any taxes, and to reimburse us, our payment affiliates, and service providers for any collection costs and interest associated with overdue amounts. If you have any disputes regarding the fees paid or payable, you must notify us in writing within fifteen (15) days of the billing date, and we will work with you to resolve the dispute promptly.

                During the free trial period or the designated number of free months, which will be indicated when you subscribe to the Service, you can use the Service without charge. After this period, your use of the Service will continue at the fees specified for the plan you selected, unless terminated.

                There may be additional fees incurred by {settings.Company} for porting your phone numbers into or out of {settings.Company}, as well as for forwarding calls in certain geographies (e.g., Alaska and the Yukon Territories). Sending or receiving SMS and MMS messages to/from certain carriers may also result in additional network or carrier-access fees. {settings.Company} reserves the right to pass these carrier-imposed costs on to you, and you agree to pay such costs.

                Please note that fees may change over time. Any charges related to your purchase or use of the Services will be billed to the credit card we have on file. If you have an ongoing Service that incurs recurring charges, such as a subscription, these charges will be billed in advance. It is your responsibility to provide accurate and up-to-date billing information, including valid credit card details, your name, address, and telephone number, and to inform us of any changes within ten (10) days.

                If your credit card is declined or the card issuer refuses to pay for the Services, {settings.Company} may suspend or terminate the Services and require you to pay any overdue amounts by alternative means acceptable to us. In the event that legal action is required to collect outstanding balances, you agree to reimburse us for all expenses incurred, including attorney fees and other legal costs.</p>

                <p><strong>Refunds:</strong>  Unless stated otherwise below, all fees paid for the Services provided on our Site are non-refundable, and we do not offer prorated refunds or credits for partially used subscriptions. However, we reserve the right to issue refunds or credits at our sole discretion. If we provide a refund or credit in one instance, we are not obligated to do so in the future.

                Additional fees may apply for in-app purchases made through the mobile app, whether through the app itself or from the original mobile-app provider, such as Apple iTunes/App Store, Google Play, Android App Store, or any other manufacturer or app store. You can review the relevant "in-app" purchase rules and policies directly from the respective app store(s). Additional terms and conditions may apply to a subscription at the time of ordering or renewal.

                Please note that your use of the Service is not dependent on the delivery of any future releases of functionality or features by us. This includes the continuation of a specific service beyond its current subscription term or any third-party services. Our public comments about future functionality or features do not create any obligations on our part regarding their implementation.</p>

                <p><strong><br/>10. Mobile Services:</strong>  The Service offers various features and functionalities that can be accessed through your mobile phone or other mobile computing device, collectively referred to as 'Mobile Services'. It's important to note that your mobile carrier will apply its standard rates, fees, and charges for messaging, data, and other mobile services when you use the Mobile Services on your phone. Additionally, please be aware that some Mobile Services may be subject to restrictions or prohibitions imposed by your mobile carrier. Not all Mobile Services may be compatible with all carriers, devices, or locations. Therefore, it is your responsibility to check with your mobile carrier to determine the availability of the Mobile Services for your specific devices, any applicable usage restrictions, and the associated costs. Regardless of any surcharges or coverage details provided by your mobile provider, your use of the Service must comply with the terms of this Agreement.</p>

                <p><strong><br/>11. Data Collection, Communications and Updates: </strong>
                By using the Service, you consent to {settings.Company} collecting certain information about your usage of the Service, including data related to your mobile device (such as device type and unique ID), operating software, feature utilization, navigation, and personal information (such as name and email). If you choose to use location-based features or services, {settings.Company} may collect your precise location. You authorize {settings.Company} to locate your device and collect, compile, and display your location information. While {settings.Company} will exercise reasonable skill and care in providing the Service, neither {settings.Company} nor its service and content providers guarantee the availability, accuracy, completeness, reliability, or timeliness of location data or any other data displayed by the Service.</p>
                <p>{settings.Company} is not responsible for the deletion or failure to store any content transmitted through the Site. Accounts that have not paid a subscription fee, remain inactive for more than one (1) year, or have violated the terms of the Agreement may be removed or terminated. We retain location information for a reasonable period to provide the Service and then delete location data tied to personal information. De-identified location data may be retained for a longer period for aggregate analysis. {settings.Company} may use and share location information with third parties for targeted advertising purposes.</p>
                <p>You agree to receive electronic communications from {settings.Company}, including notices about fees, transactional information, and other Service-related communications. These electronic communications fulfill your legal communication requirements. Additionally, when you install the Service, you may download updates and upgrades to fix defects or provide enhancements. You will be given notice and the option to accept or refuse updates or upgrades, although refusing them may impact the performance of the Service.
                </p>

                <p><strong><br/>12. Privacy Policy and Opt-Out</strong> - For detailed information regarding {settings.Company}'s data collection and use, including location-based and personally identifiable information, please refer to {settings.Company}'s Privacy Policy available at <a href={`${settings.URL}/privacy-policy`} className="anchor">{settings.URL}/privacy-policy.html</a>. The Privacy Policy outlines how {settings.Company} handles the collection of information through the Service and provides options for opting out of certain information collection. Please note that opting out may only apply to the specific browser or device used for opting out and not to the entire privacy policy or its provisions.</p>

                <p><strong><br/>13. Feedback:</strong>  {settings.Company} values your feedback and suggestions to enhance their products and services, including the Service. By sending any suggestions, information, materials, or other content (referred to as "Feedback") to {settings.Company}, you confirm that the Feedback does not infringe upon or violate any third-party intellectual property or proprietary rights, such as patents, copyrights, or trademarks. Furthermore, you assert that you possess all the necessary rights to convey and enable {settings.Company} to use the Feedback. Any Feedback received by {settings.Company} will be considered as granting a royalty-free, perpetual, irrevocable, transferable, non-exclusive right and license for {settings.Company} to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works of, and display (in whole or in part) the Feedback worldwide. {settings.Company} is authorized to act upon the Feedback without requiring additional approval or consideration, in any form, media, or technology, whether known or developed in the future, for the entire duration of any existing rights. By providing Feedback, you waive any claim to the contrary.</p>

                <p><strong><br/>14. TO OTHER SITES:</strong>  The Service may provide links to third-party websites or online networks (referred to as "Third Party Sites"). These Third-Party Sites are not reviewed or controlled by {settings.Company} and are solely owned, controlled, and maintained by third parties. Any correspondence or dealings with third parties through Third Party Sites found on the Service are solely between you and those third parties. Therefore, {settings.Company} explicitly disclaims any liability or responsibility for any Third Party Sites.</p>

                <p><strong><br/>15. PROPRIETARY RIGHTS:</strong>  This Agreement grants you a limited license to access and use the Service according to its terms. However, {settings.Company} does not transfer any ownership, intellectual property interest, or title of the Service or any other {settings.Company} intellectual property to you or anyone else in connection with your use of the Service. All content on the Service, including text, graphics, photographs, computer code, software, trademarks, and the design and arrangement thereof, is exclusively owned, controlled, and/or licensed by {settings.Company} or its affiliate(s). {settings.Company}'s trademarks and other marks identifying its products or services are proprietary and unauthorized use of such marks, including as domain names or account identifiers, or in connection with any search engine optimization practices, is strictly prohibited without prior written permission from {settings.Company}.</p>

                <p><strong><br/>16. CONFIDENTIALITY:</strong>  You acknowledge and agree that the Service contains valuable trade secrets and confidential information of {settings.Company} and/or its licensors (referred to as "Confidential Information"). You are obligated to maintain the confidentiality of {settings.Company}'s Confidential Information and protect it with the same level of care you would use for your own confidential information of a similar nature. This includes not selling, transferring, publishing, disclosing, or making any portion of the Confidential Information available to third parties, except as expressly authorized in this Agreement. The term "Confidential Information" refers to any information or data, whether tangible or not, that is marked or designated as confidential or proprietary, or that should reasonably be understood as confidential based on the nature of the information and the circumstances of disclosure. However, Confidential Information does not include information that: (a) is publicly available without the receiving party's fault; (b) the receiving party knew prior to disclosure without any restrictions; (c) was properly disclosed to the receiving party by another person without violating the disclosing party's rights; or (d) is independently developed by the receiving party without using or referring to the Confidential Information of the disclosing party.</p>

                <p><strong><br/>17. NO AGENCY RELATIONSHIP:</strong>  These Terms of Use do not create or imply any partnership, joint venture, employment, or agency relationship between us. There is no intention to enter into any contract on our behalf or to bind us in any manner.</p>

                <p><strong><br/>18. DISCLAIMER:</strong>  THE SERVICE IS PROVIDED ON AN "AS-IS" BASIS AND MAY CONTAIN ERRORS, OMISSIONS, OR OTHER INACCURACIES. {settings.Company} EXPLICITLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ANY OTHER IMPLIED WARRANTY UNDER THE UNIFORM COMPUTER INFORMATION TRANSACTIONS ACT AS ENACTED BY ANY STATE. TO THE EXTENT PERMITTED BY APPLICABLE LAW, {settings.Company} DOES NOT GUARANTEE OR WARRANT THAT ANY CONTENT YOU STORE OR ACCESS THROUGH THE SERVICE WILL BE FREE FROM INADVERTENT DAMAGE, CORRUPTION, LOSS, OR REMOVAL IN ACCORDANCE WITH THE TERMS OF THIS AGREEMENT. {settings.Company} ALSO MAKES NO REPRESENTATIONS OR WARRANTIES THAT THE SERVICE WILL OPERATE ERROR-FREE, UNINTERRUPTED, OR IN A MANNER THAT MEETS YOUR SPECIFIC REQUIREMENTS AND NEEDS. THEREFORE, YOU ASSUME ALL RISKS ASSOCIATED WITH THE QUALITY AND PERFORMANCE OF THE SERVICE. YOU ACKNOWLEDGE THAT {settings.Company} IS NOT LIABLE FOR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF OTHER USERS OR THIRD PARTIES OVER WHOM IT HAS NO CONTROL.</p>

                <p>{settings.Company} ASSUMES NO LIABILITY FOR FAILURE OR DELAY IN PERFORMANCE, WHETHER IN PART OR IN WHOLE. ADDITIONALLY, {settings.Company} IS NOT LIABLE FOR ANY CLAIMS OR DAMAGES RESULTING FROM YOUR USE OF THE SERVICE.</p>

                <p><strong><br/>19. LIMITATION OF LIABILITY:</strong>  YOU EXPRESSLY RELEASE AND ABSOLVE {settings.Company} FROM ANY CLAIMS OF HARM ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO EQUIPMENT OR COMMUNICATION FAILURES, CONNECTION PROBLEMS, COMPUTER VIRUSES, UNAUTHORIZED ACCESS, THEFT, OPERATOR ERRORS, SEVERE WEATHER, NATURAL DISASTERS, STRIKES, OR GOVERNMENTAL RESTRICTIONS. FURTHERMORE, TO THE MAXIMUM EXTENT PERMITTED BY LAW, {settings.Company} SHALL NOT BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO ANY DEALINGS OR AGREEMENTS BETWEEN YOU AND A THIRD PARTY, THE DELAY OR INABILITY TO USE THE SERVICE, THE COST OF OBTAINING SUBSTITUTE PRODUCTS OR SERVICES, OR ANY INFORMATION, SOFTWARE FUNCTIONALITY, AND MATERIALS AVAILABLE THROUGH THE SERVICE, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, EVEN IF {settings.Company} HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ADDITIONALLY, THE TOTAL LIABILITY OF {settings.Company} FOR ANY REASON RELATED TO THE USE OF THE SERVICE SHALL NOT EXCEED $100 (US) OR THE AMOUNT PAID BY YOU TO {settings.Company} FOR THE USE OF THE SERVICE DURING THE TWELVE (12) MONTHS PRECEDING ANY CLAIM, WHICHEVER IS GREATER. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS OF LIABILITY IN THIS AGREEMENT SHALL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>

                <p><strong><br/>20. INDEMNIFICATION:</strong>  You agree to indemnify, defend, and hold {settings.Company} (and its affiliated companies, contractors, employees, agents, suppliers, and partners) harmless from any claims, suits, actions, liabilities, losses, costs, damages, expenses, and other liabilities, including attorneys' fees, arising from or related to your use or misuse of the Service, including but not limited to your access to or use of the Service, any breach or alleged violation of the rights of any other person or entity by you, including intellectual property rights, publicity rights, confidentiality, property rights, or privacy rights, and any breach or alleged violation of this Agreement by you.</p>

                <p><strong><br/>21. SECURITY AND ENFORCEMENT:</strong>   {settings.Company} reserves the right in its sole discretion to review, monitor, and/or record any information relating to your use of the Service ("User Information") without any prior notice to or permission from you, including, without limitation, by archiving content and/or communications submitted to and/or sent by you through the Service. {settings.Company} may share any User Information obtained from you with any law enforcement organization in connection with any investigation or prosecution of possible criminal or unlawful activity. {settings.Company} will also disclose User Information as required by any court order and/or subpoena.</p>
                <p>In addition, {settings.Company} reserves the right in its sole discretion to, at any time and without notice, modify, suspend, terminate, and/or interrupt the operation of or access to the Service, or any portion thereof, in order to protect the Service, {settings.Company}'s intellectual property, {settings.Company}, or the business interests of {settings.Company} and/or its members and affiliates.</p>
                <p>{settings.Company} shall not be liable to you or to any third party for any such modifications, suspensions, or discontinuances of the Service or subscriptions to the Service, and shall have no obligation to refund any fees paid pursuant to this Agreement except for fees that are prepaid but unused at the time of termination in the event {settings.Company} terminates this Agreement for convenience.</p>

                <p><strong><br/>22. INJUNCTIVE RELIEF:</strong>   You acknowledge that any breach, threatened or actual, of this Agreement, including, without limitation, violations or infringement of {settings.Company}'s intellectual property or proprietary rights, may cause irreparable injury to {settings.Company}. The resulting injury may not be quantifiable in monetary damages, and {settings.Company} may not have an adequate remedy at law. Therefore, in the event of such injury or potential for such injury, you agree that {settings.Company} shall be entitled, in addition to other available remedies, to seek and be awarded an injunction or other appropriate equitable relief from a court of competent jurisdiction to restrain any breach, threatened or actual, of your obligations under any provision of this Agreement.</p>

                <p><strong><br/>23. GOVERNING LAW:</strong>   This Agreement has been made in and will be construed and enforced in accordance with the laws of the State of Texas. It applies to agreements entered into and completely performed within the State of Texas. By agreeing to this Agreement, you submit to the exclusive personal jurisdiction and venue of any federal or state court in the State of Texas. You also waive any objection to such jurisdiction or venue and agree to a jury trial in any action. You acknowledge and agree that any applicable state law implementation of the Uniform Computer Information Transactions Act is disclaimed and does not apply to this Agreement. Any claim you may have against {settings.Company} must be brought within one (1) year after the cause of action arises, or the claim or cause of action is barred. In any legal proceeding brought by {settings.Company}, {settings.Company} has the right to seek and be awarded all reasonable attorneys' fees and costs, in addition to any other relief, whether at law or in equity, to which {settings.Company} may be entitled. A printed version of this Agreement and any related notice given in electronic form is admissible in judicial or administrative proceedings relating to this Agreement, to the same extent as other documents and records originally generated and maintained in printed form. If you wish to receive a printed copy of this Agreement, please print a copy or contact {settings.Company}.</p>

                <p><strong><br/>24. USER COMPLIANCE WITH ALL LAWS:</strong>  You are responsible for ensuring that your use of the Services complies with all applicable laws, regulations, and policies. This includes adhering to the {settings.Company} Privacy Policy, these Terms of Use, and any other relevant laws and regulations in your jurisdiction. You must comply with local laws and regulations regarding online conduct, acceptable content, and data transmission, including any laws related to the export of data, software, technology, or technical data from the United States, Canada, or your country of residence.
                
                Furthermore, you warrant that your collection and use of personally identifiable information and technical data will comply with all applicable federal, provincial, state, and local laws, rules, and regulations. This includes privacy, confidentiality, security, management, disclosure, reporting, and other obligations related to personally identifiable information or technical data. Examples of such laws may include the CAN-SPAM Act, the Telephone Consumer Protection Act (TCPA), the Personal Information Protection and Electronic Documents Act (PIPEDA), and the Canadian Anti-Spam Law (CASL), among others (collectively referred to as "Privacy Laws and Regulations").
                
                Failure to comply with Privacy Laws and Regulations will be considered a material breach of these Terms of Service and may result in the immediate suspension or termination of your account, as well as potential civil and/or criminal liability. It is your responsibility to determine whether the Service is suitable for your use considering your obligations under relevant regulations such as HIPAA, GLB, EU data privacy laws, US export control laws and regulations, economic sanctions laws and regulations, or any other applicable laws. If you are subject to specific regulations (e.g., HIPAA) and you choose to use the Service, we will not be held liable if the Service does not meet those requirements.</p>

                <p><strong><br/>25. TERM AND TERMINATION:</strong>  This Agreement will take (re-take) effect at the time you click "I ACCEPT", download the Service, or begin using the Service, whichever is earliest. You have the option to uninstall or delete the Service at any time using the available uninstall or delete functionality provided by the applicable operating software or mobile device. However, by uninstalling or deleting the Service, you will no longer be able to access the Service's functionality or related services, and you will not be entitled to any refund of subscription fees. This Agreement will automatically terminate if 
                </p><div className="square-ul"><ul className='list-disc list-inside mb-4 font-semibold'>
                <li>you fail to comply with any of its terms and conditions, or </li><li>you cease all use of the Service.</li>
                </ul></div>
                Termination will be effective without notice. Additionally, {settings.Company} reserves the right to terminate this Agreement or suspend the service upon notice to you for any reason or no reason at all, at its sole discretion. Upon termination of this Agreement, your right to use the Service will immediately cease, and you must promptly delete or destroy all copies of the Service in your possession or control.

                <p><strong><br/>26. WAIVER AND SEVERABILITY:</strong>  {settings.Company}'s failure to insist upon strict performance of any of the terms and conditions of this Agreement by you will not operate as a waiver of any subsequent default or failure of performance. If any part of this Agreement is determined by a court of competent jurisdiction to be invalid or unenforceable pursuant to applicable law or court order, including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision(s) that most clearly matches the intent of the original provision, and the remainder of this Agreement shall continue in effect.</p>

                <p><strong><br/>27. MODIFICATIONS TO THESE TERMS:</strong>  These Terms of Use are subject to change. {settings.Company} has the right to modify these terms and conditions at any time by posting or sending you a revised version of the Agreement. This may be done without advance notice to you. Therefore, it is advisable to review the terms and conditions periodically at the provided location. Each time you access the Service, you agree to be bound by the Agreement in effect at the time of access. If you do not agree to the revised terms, you should not use the Service.</p>

                <p><strong><br/>28. MISCELLANEOUS: </strong> 

                This Agreement operates in addition to any terms of use imposed or required by digital download platforms such as Apple Inc., Google Inc., Microsoft Inc., or any other platform from which you download the Service.

                The terms of this Agreement supplement and do not alter or amend any App Provider Terms.
                There is no joint venture, partnership, employment, or agency relationship between you and {settings.Company} resulting from this Agreement or your use of the Service.
                Headings in the Agreement are for convenience only.

                This Agreement, along with {settings.Company}'s Privacy Policy found at <a href={`${settings.URL}/privacy-policy`} className="anchor"><span className='light-500'>{settings.URL}/privacy-policy.html</span></a>, represents the entire agreement between you and {settings.Company} regarding the use of the Service, superseding all prior communications and proposals.
                You cannot assign, delegate, or transfer any rights under this Agreement without the prior written consent of {settings.Company}, which may be withheld at {settings.Company}'s sole discretion.
                Please note that the information provided is a summary, and the actual terms and conditions of the agreement should be referred to for complete and accurate details.</p>

                <p><strong><br/>CONTACT US</strong></p>
                <a href={`mailto:${settings.Email}`}><span className='light-500'>{settings.Email}</span></a>
            </main>
            <Footer />
        </div>
    );
};

export default TermsOfUse;
